---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v3.29.1
      hooks:
          - id: commitizen
            stages: [commit-msg]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-ast
            stages: [Nonepre-commitNone]
          - id: end-of-file-fixer
            stages: [Nonepre-commitNone]
          - id: mixed-line-ending
            stages: [Nonepre-commitNone]
          - id: check-toml
            stages: [Nonepre-commitNone]
          - id: trailing-whitespace
            exclude: cm-cfg
            stages: [Nonepre-commitNone]
          - id: check-docstring-first
            stages: [Nonepre-commitNone]
          - id: check-yaml
            stages: [Nonepre-commitNone]
          - id: check-json
            stages: [Nonepre-commitNone]
          - id: pretty-format-json
            args: [--autofix, --indent=4]
            stages: [Nonepre-commitNone]
          - id: check-added-large-files
            stages: [Nonepre-commitNone]
          - id: requirements-txt-fixer
            stages: [Nonepre-commitNone]
          - id: check-merge-conflict
            stages: [Nonepre-commitNone]
          - id: debug-statements
            stages: [Nonepre-commitNone]
          - id: check-executables-have-shebangs
            language: python
            files: \.py$
            stages: [Nonepre-commitNone]
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.5
      hooks:
          - id: remove-crlf
            stages: [Nonepre-commitNone]
          - id: remove-tabs
            exclude: cm-cfg
            stages: [Nonepre-commitNone]
          - id: forbid-crlf
            stages: [Nonepre-commitNone]
          - id: forbid-tabs
            exclude: cm-cfg
            stages: [Nonepre-commitNone]
    - repo: https://github.com/myint/eradicate
      rev: 2.3.0
      hooks:
          - id: eradicate
            name: eradicate
            description: Apply eradicate
            entry: eradicate
            language: python
            files: \.py$
            args: [--in-place]
            stages: [Nonepre-commitNone]
    - repo: https://github.com/PyCQA/isort
      rev: 5.13.2
      hooks:
          - id: isort
            name: isort
            entry: isort
            require_serial: true
            language: python
            types: [python]
            stages: [Nonepre-commitNone]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.6.9
      hooks:
          - id: ruff
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.17.0
      hooks:
          - id: pyupgrade
            args: [--py39-plus]
            stages: [Nonepre-commitNone]
    - repo: https://github.com/ikamensh/flynt/
      rev: 1.0.1
      hooks:
          - id: flynt
            stages: [Nonepre-commitNone]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
            stages: [Nonepre-commitNone]
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.35.1
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]
            stages: [Nonepre-commitNone]
    - repo: https://github.com/psf/black
      rev: 24.8.0
      hooks:
          - id: black
            description: 'Black: The uncompromising Python code formatter'
            args: [--safe]
            stages: [Nonepre-commitNone]
    - repo: https://github.com/akaihola/darglint2
      rev: v1.8.2
      hooks:
          - id: darglint2
    - repo: local
      hooks:
          - id: nox
            name: nox
            entry: nox
            language: system
            stages: [Nonepre-pushNone]
            pass_filenames: false
            types: [python]
